import { Recipe } from './interfaces/recipe';

export let RECIPES: Recipe[] = [
  {
    id: 1,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 2,
    title: 'Veggie Dinner',
    time: 130,
    tags: [
      'Vegetarian',
      'Dinner',
      'Salad',
      'Quick',
      'Fast',
      'Easy',
      'Indian',
      'Big Servings',
      'Healthy',
      'Quick',
      'Fast',
      'Easy',
    ],
    primaryTag: 'Dinner',
    serves: 2,
    imageSrc: '../../assets/images/test1.jpg',
    favorite: false,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: [
      'Place flour in bowl',
      'mix in baking soda',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    ],
    notes: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
  },
  {
    id: 3,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 4,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 5,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 6,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 7,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda', ''],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 8,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
  {
    id: 1,
    title: 'One Pot Italian',
    time: 120,
    tags: ['Vegetarian, Dinner'],
    primaryTag: 'Vegetarian',
    serves: 2,
    imageSrc: '../../assets/images/PlaceholderImage.jpg',
    favorite: true,
    ingredients: ['1 cup flour', '2 teaspoons baking soda'],
    instructions: ['Place flour in bowl', 'mix in baking soda'],
    notes: ['Note 1', 'Note 2', 'Note 3'],
  },
];
